export const ADDCARDMM = "ADDCARDMM";
export const REMOVECARDMM = "REMOVECARDMM";
export const EMPTYCARDMM = "EMPTYCARDMM";
export const BLOCK_GET_PRODUCTS = "BLOCK_GET_PRODUCTS";
export const BLOCK_SET_PRODUCTS = "BLOCK_SET_PRODUCTS";
